export enum SyntaxKind {
  // Composite nodes
  DOCUMENT = "DOCUMENT",
  ATX_HEADING = "ATX_HEADING",
  PARAGRAPH = "PARAGRAPH",
  THEMATIC_BREAK = "THEMATIC_BREAK",
  LIST = "LIST",
  LIST_ITEM = "LIST_ITEM",

  // Tokens
  HASH = "HASH",
  WHITESPACE = "WHITESPACE",
  NEWLINE = "NEWLINE",
  TEXT = "TEXT",
  MARKER = "MARKER",
  THEMATIC_BREAK_CHARS = "THEMATIC_BREAK_CHARS",
  BLANK_LINE = "BLANK_LINE",
  EOF = "EOF",
}
