export enum SyntaxKind {
  // Composite nodes - Block
  DOCUMENT = "DOCUMENT",
  ATX_HEADING = "ATX_HEADING",
  PARAGRAPH = "PARAGRAPH",
  THEMATIC_BREAK = "THEMATIC_BREAK",
  LIST = "LIST",
  LIST_ITEM = "LIST_ITEM",
  FENCED_CODE_BLOCK = "FENCED_CODE_BLOCK",
  BLOCK_QUOTE = "BLOCK_QUOTE",

  // Composite nodes - Inline
  CODE_SPAN = "CODE_SPAN",
  EMPHASIS = "EMPHASIS",
  STRONG_EMPHASIS = "STRONG_EMPHASIS",
  LINK = "LINK",
  IMAGE = "IMAGE",
  LINK_TEXT = "LINK_TEXT",
  IMAGE_ALT = "IMAGE_ALT",

  // Tokens - Block
  HASH = "HASH",
  WHITESPACE = "WHITESPACE",
  NEWLINE = "NEWLINE",
  TEXT = "TEXT",
  MARKER = "MARKER",
  THEMATIC_BREAK_CHARS = "THEMATIC_BREAK_CHARS",
  BLANK_LINE = "BLANK_LINE",
  EOF = "EOF",
  CODE_FENCE = "CODE_FENCE",
  INFO_STRING = "INFO_STRING",
  CODE_CONTENT = "CODE_CONTENT",
  BLOCK_QUOTE_MARKER = "BLOCK_QUOTE_MARKER",

  // Tokens - Inline
  BACKTICK = "BACKTICK",
  EMPHASIS_MARKER = "EMPHASIS_MARKER",
  HARD_LINE_BREAK = "HARD_LINE_BREAK",
  LINK_OPEN = "LINK_OPEN",
  LINK_CLOSE = "LINK_CLOSE",
  IMAGE_OPEN = "IMAGE_OPEN",
  LINK_DEST_OPEN = "LINK_DEST_OPEN",
  LINK_DEST_CLOSE = "LINK_DEST_CLOSE",
  LINK_DESTINATION = "LINK_DESTINATION",
  LINK_TITLE = "LINK_TITLE",
}
